-- Sample Package Data for Testing
-- Run this in your Supabase SQL Editor

INSERT INTO packages (
  name, 
  description, 
  destination, 
  country, 
  category, 
  duration_days, 
  price, 
  currency,
  max_participants, 
  available_slots, 
  difficulty_level,
  minimum_age,
  included_services,
  excluded_services,
  contact_email, 
  contact_phone, 
  cover_image,
  images,
  rating,
  reviews_count
) VALUES 
  (
    'Cox''s Bazar Beach Paradise',
    'Experience the world''s longest natural sea beach! Enjoy pristine beaches, fresh seafood, and beautiful sunsets. Perfect for families and couples.',
    'Cox''s Bazar',
    'Bangladesh',
    'Beach',
    3,
    299.00,
    'USD',
    10,
    8,
    'Easy',
    0,
    ARRAY['Hotel Accommodation', 'Breakfast', 'Beach Activities', 'Guide Service', 'Transport'],
    ARRAY['Lunch', 'Dinner', 'Personal Expenses'],
    'info@gotravel.com',
    '+880-1234-567890',
    'https://images.unsplash.com/photo-1559827260-dc66d52bef19',
    ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e'],
    4.5,
    127
  ),
  (
    'Sundarbans Mangrove Adventure',
    'Explore the largest mangrove forest in the world! Cruise through narrow channels, spot Royal Bengal Tigers, and experience unique wildlife.',
    'Sundarbans',
    'Bangladesh',
    'Wildlife',
    2,
    450.00,
    'USD',
    6,
    4,
    'Moderate',
    12,
    ARRAY['Boat Cruise', 'Wildlife Guide', 'All Meals', 'Accommodation', 'Binoculars'],
    ARRAY['Personal Insurance', 'Camera Fees'],
    'info@gotravel.com',
    '+880-1234-567890',
    'https://images.unsplash.com/photo-1564760055775-d63b17a55c44',
    ARRAY['https://images.unsplash.com/photo-1564760055775-d63b17a55c44'],
    4.8,
    93
  ),
  (
    'Sylhet Tea Garden Tour',
    'Visit the picturesque tea estates of Sylhet! Experience lush green hills, tea picking, and taste fresh tea. Includes visits to Ratargul Swamp Forest.',
    'Sylhet',
    'Bangladesh',
    'Nature',
    2,
    199.00,
    'USD',
    12,
    10,
    'Easy',
    0,
    ARRAY['Tea Garden Tours', 'Breakfast', 'Local Transport', 'Guide'],
    ARRAY['Lunch', 'Dinner', 'Shopping'],
    'info@gotravel.com',
    '+880-1234-567890',
    'https://images.unsplash.com/photo-1563789031959-4c02bcb41319',
    ARRAY['https://images.unsplash.com/photo-1563789031959-4c02bcb41319'],
    4.3,
    68
  ),
  (
    'Dhaka Heritage Walk',
    'Discover the rich history of Old Dhaka! Visit Lalbagh Fort, Ahsan Manzil, Armenian Church, and explore bustling streets and authentic cuisine.',
    'Dhaka',
    'Bangladesh',
    'Cultural',
    1,
    89.00,
    'USD',
    15,
    12,
    'Easy',
    8,
    ARRAY['Walking Tour', 'Entry Fees', 'Traditional Lunch', 'Professional Guide'],
    ARRAY['Transport to/from Hotel', 'Personal Expenses'],
    'info@gotravel.com',
    '+880-1234-567890',
    'https://images.unsplash.com/photo-1554797589-7241bb691973',
    ARRAY['https://images.unsplash.com/photo-1554797589-7241bb691973'],
    4.6,
    156
  ),
  (
    'Bandarban Hill Tracts Trekking',
    'Trek through the beautiful hills of Bandarban! Experience indigenous culture, visit tribal villages, and enjoy breathtaking mountain views.',
    'Bandarban',
    'Bangladesh',
    'Adventure',
    4,
    380.00,
    'USD',
    8,
    6,
    'Challenging',
    16,
    ARRAY['Trekking Guide', 'Camping Equipment', 'All Meals', 'Village Homestay', 'Permits'],
    ARRAY['Personal Trekking Gear', 'Travel Insurance'],
    'info@gotravel.com',
    '+880-1234-567890',
    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
    ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4'],
    4.7,
    84
  ),
  (
    'Chittagong Port City Experience',
    'Explore Bangladesh''s main seaport! Visit Foy''s Lake, Patenga Beach, ship breaking yards, and enjoy fresh seafood at local restaurants.',
    'Chittagong',
    'Bangladesh',
    'City',
    2,
    149.00,
    'USD',
    10,
    8,
    'Easy',
    0,
    ARRAY['Hotel Stay', 'Breakfast', 'City Tour', 'Transport'],
    ARRAY['Lunch', 'Dinner', 'Shopping'],
    'info@gotravel.com',
    '+880-1234-567890',
    'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b',
    ARRAY['https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b'],
    4.2,
    72
  );

-- Verify the data was inserted
SELECT name, destination, price, category, available_slots 
FROM packages 
ORDER BY price ASC;
